### ISSUE TITLE
support BUSD ?

### ISSUE THREAD

**Issue by internalsync** [ZainAchak/DeFi_PanCakeSwapBot#13]
Support BUSD liquidity ？

**Comment by HHawk** [comment]
It seems ZainAchak is not around anymore.
I cannot even get the bot to work. :-( 👎

**Comment by ZainAchak** [comment]
@internalsync BUSD is not supported right now but In next update maybe I'll add that.

**Comment by ZainAchak** [comment]
@HHawk Sorry I am busy a lot these days, But I tried the script now and it seems to work for me.
