### ISSUE TITLE
On Ubuntu 20.04

### ISSUE THREAD

**Issue by mykaelHunter** [ZainAchak/DeFi_PanCakeSwapBot#16]
issue with bs4 getting price from arken finance

line 125, in runCode
price = float(page_soup.find_all("b", {"class": "number"})[0].text[1:].replace(",", ""))
IndexError: list index out of range

No matter what I do, I keep running into this error
I have fixed the clear command, I have tried using only Firefox drives instead of Chrome, I have tried different contact addresses, this error always comes out, I'm a noob to python and javascript

**Comment by ZainAchak** [comment]
> This error occurs when scripts can't find arken website. I didn't tried it on Ubuntu try to run it on Windows it'll work for you.
