### ISSUE TITLE
Unable to run Bot

### ISSUE THREAD

**Issue by Angel2298** [ZainAchak/DeFi_PanCakeSwapBot#2]
So I was able to to start the bot, but after I enter the contract I got an error. 

![image](https://user-images.githubusercontent.com/80131965/132107821-904971d2-7129-4fa1-abe5-5055684cfa4e.png)

First of all I got an error with lxml. 
So for that I just did `pip install lxml` and the error was corrected. But know this is the error that I got and I don´t know why cause I just checked all the code in that part and also I tried with the ETCH contract that you use in the video and got the same error that "list out of index"

**Comment by Angel2298** [comment]
Or maybe it is that the version of lxml is not compatible. Which version are you using?

**Comment by ZainAchak** [comment]
Already resolved you can check it now, Enjoy
