### ISSUE TITLE
Feature request - Automation

### ISSUE THREAD

**Issue by markbell2410** [ZainAchak/DeFi_PanCakeSwapBot#5]
This is a solid project. I would like to see an extension that I think would add value to the bot.

# Scenario 1 (Fixed limits)
* The ability to set a static range with low and high inputs. 
* This would allow the user to enter a low of 0.1 for example, so the script would buy at $0.10. 
* The user could also set a high of 0.9 and the script would sell at $0.90
* Considerations would be to add logic so that the script knows whether the last action was a buy or sell, so it will ignore a buy signal if the last was a buy

# Scenario 2 (Percentage based limits)
* The ability to set a percentage based range
* The user can set the script to buy when the current price is n% lower than the last sell price
* The user can set the script to sell when the current price is n% higher than the last buy price

## Addtional considerations
* DCA in/out
* Add percentage of account value 

I will record a priv. screencast detailing the aforementioned scenario

**Comment by ZainAchak** [comment]
> How can I reach you, Zain? 
> [Mark](https://twitter.com/markbell2410)

[LinkedIn](https://www.linkedin.com/in/zain-ullah-466aa4125)

**Comment by markbell2410** [comment]
DM is a premium feature on LI!

**Comment by ZainAchak** [comment]
Will Update it soon, already finished working on that.
