### ISSUE TITLE
Issue Sell

### ISSUE THREAD

**Issue by aleeepp** [ZainAchak/DeFi_PanCakeSwapBot#6]
Hi great project!!!

I get this error when trying to sell : "Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'"

Do you have an idea of ​​the isseu?

**Comment by ZainAchak** [comment]
Try to Change the GAS value in the code for BuyTokens.py or SellTokens.py, As the tokens you want to buy need extra Gas fees, so increase that and you're good to go. 👍
