### ISSUE TITLE
Run on linux?

### ISSUE THREAD

**Issue by Eimuex** [ZainAchak/DeFi_PanCakeSwapBot#8]
Hello, I tried to run bot on linux and got:

Traceback (most recent call last):
  File "DeFiTranscation.py", line 9, in <module>
    import winsound
ModuleNotFoundError: No module named 'winsound'

I found that winsound is windows only module. Is there any possible workaround?
Thank you

**Comment by ZainAchak** [comment]
You can run it on Linux smoothly but you have to replace winsound to some sound library for Linux, else everything will go smooth.
